# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-on-linux:
    runs-on: ubuntu-latest

    steps:
            
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Displaying flutter version
        run: flutter --version
        
      - name: Running pub get
        run: flutter pub get
        
      - name: Build apk
        run: flutter build apk
        
      - name: Build app bundle
        run: flutter build appbundle
        
      - name: Build linux app
        run: flutter build linux --release
        
      - name: Upload apk
        uses: actions/upload-artifact@v4        
        with:
          name: OrsNews.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
      - name: Upload aab
        uses: actions/upload-artifact@v4
        with:
          name: OrsNews.aab
          path: build/app/outputs/bundle/release/app-release.aab
