# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
            
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
